//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI_Hotel_Booking.LocalizationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", ConfigurationName="LocalizationService.LocalizationWebService")]
    public interface LocalizationWebService {
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.ws.project.soap.rsi.com/LocalizationWebService/getLocalizationLis" +
            "tDtoRequest", ReplyAction="http://endpoint.ws.project.soap.rsi.com/LocalizationWebService/getLocalizationLis" +
            "tDtoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RSI_Hotel_Booking.LocalizationService.getLocalizationListDtoResponse getLocalizationListDto(RSI_Hotel_Booking.LocalizationService.getLocalizationListDtoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.ws.project.soap.rsi.com/LocalizationWebService/getLocalizationLis" +
            "tDtoRequest", ReplyAction="http://endpoint.ws.project.soap.rsi.com/LocalizationWebService/getLocalizationLis" +
            "tDtoResponse")]
        System.Threading.Tasks.Task<RSI_Hotel_Booking.LocalizationService.getLocalizationListDtoResponse> getLocalizationListDtoAsync(RSI_Hotel_Booking.LocalizationService.getLocalizationListDtoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/")]
    public partial class localizationDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private string photoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
                this.RaisePropertyChanged("photo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLocalizationListDto", WrapperNamespace="http://endpoint.ws.project.soap.rsi.com/", IsWrapped=true)]
    public partial class getLocalizationListDtoRequest {
        
        public getLocalizationListDtoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLocalizationListDtoResponse", WrapperNamespace="http://endpoint.ws.project.soap.rsi.com/", IsWrapped=true)]
    public partial class getLocalizationListDtoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RSI_Hotel_Booking.LocalizationService.localizationDto[] @return;
        
        public getLocalizationListDtoResponse() {
        }
        
        public getLocalizationListDtoResponse(RSI_Hotel_Booking.LocalizationService.localizationDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LocalizationWebServiceChannel : RSI_Hotel_Booking.LocalizationService.LocalizationWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocalizationWebServiceClient : System.ServiceModel.ClientBase<RSI_Hotel_Booking.LocalizationService.LocalizationWebService>, RSI_Hotel_Booking.LocalizationService.LocalizationWebService {
        
        public LocalizationWebServiceClient() {
        }
        
        public LocalizationWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocalizationWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalizationWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalizationWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RSI_Hotel_Booking.LocalizationService.getLocalizationListDtoResponse RSI_Hotel_Booking.LocalizationService.LocalizationWebService.getLocalizationListDto(RSI_Hotel_Booking.LocalizationService.getLocalizationListDtoRequest request) {
            return base.Channel.getLocalizationListDto(request);
        }
        
        public RSI_Hotel_Booking.LocalizationService.localizationDto[] getLocalizationListDto() {
            RSI_Hotel_Booking.LocalizationService.getLocalizationListDtoRequest inValue = new RSI_Hotel_Booking.LocalizationService.getLocalizationListDtoRequest();
            RSI_Hotel_Booking.LocalizationService.getLocalizationListDtoResponse retVal = ((RSI_Hotel_Booking.LocalizationService.LocalizationWebService)(this)).getLocalizationListDto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RSI_Hotel_Booking.LocalizationService.getLocalizationListDtoResponse> RSI_Hotel_Booking.LocalizationService.LocalizationWebService.getLocalizationListDtoAsync(RSI_Hotel_Booking.LocalizationService.getLocalizationListDtoRequest request) {
            return base.Channel.getLocalizationListDtoAsync(request);
        }
        
        public System.Threading.Tasks.Task<RSI_Hotel_Booking.LocalizationService.getLocalizationListDtoResponse> getLocalizationListDtoAsync() {
            RSI_Hotel_Booking.LocalizationService.getLocalizationListDtoRequest inValue = new RSI_Hotel_Booking.LocalizationService.getLocalizationListDtoRequest();
            return ((RSI_Hotel_Booking.LocalizationService.LocalizationWebService)(this)).getLocalizationListDtoAsync(inValue);
        }
    }
}
