//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI_Hotel_Booking.BookingService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", ConfigurationName="RSI_Hotel_Booking.BookingService.BookingWebService")]
    public interface BookingWebService
    {
        
        [System.ServiceModel.OperationContractAttribute()]
        void getBookingViewDtos();
        
        [System.ServiceModel.OperationContractAttribute()]
        void getBookingViewDtosAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void booking();
        
        [System.ServiceModel.OperationContractAttribute()]
        void bookingAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void checkAvailable();
        
        [System.ServiceModel.OperationContractAttribute()]
        void checkAvailableAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookingWebServiceChannel : RSI_Hotel_Booking.BookingService.BookingWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookingWebServiceClient : System.ServiceModel.ClientBase<RSI_Hotel_Booking.BookingService.BookingWebService>, RSI_Hotel_Booking.BookingService.BookingWebService
    {
        
        public BookingWebServiceClient()
        {
        }
        
        public BookingWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public BookingWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BookingWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BookingWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void getBookingViewDtos()
        {
            base.Channel.getBookingViewDtos();
        }
        
        public void getBookingViewDtosAsync()
        {
            base.Channel.getBookingViewDtosAsync();
        }
        
        public void booking()
        {
            base.Channel.booking();
        }
        
        public void bookingAsync()
        {
            base.Channel.bookingAsync();
        }
        
        public void checkAvailable()
        {
            base.Channel.checkAvailable();
        }
        
        public void checkAvailableAsync()
        {
            base.Channel.checkAvailableAsync();
        }
    }
}
