//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI_Hotel_Booking.HotelService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", ConfigurationName="RSI_Hotel_Booking.HotelService.HotelWebService")]
    public interface HotelWebService
    {
        
        [System.ServiceModel.OperationContractAttribute()]
        void getHotelListDto();
        
        [System.ServiceModel.OperationContractAttribute()]
        void getHotelListDtoAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void getHotelDto();
        
        [System.ServiceModel.OperationContractAttribute()]
        void getHotelDtoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HotelWebServiceChannel : RSI_Hotel_Booking.HotelService.HotelWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelWebServiceClient : System.ServiceModel.ClientBase<RSI_Hotel_Booking.HotelService.HotelWebService>, RSI_Hotel_Booking.HotelService.HotelWebService
    {
        
        public HotelWebServiceClient()
        {
        }
        
        public HotelWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public HotelWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HotelWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HotelWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void getHotelListDto()
        {
            base.Channel.getHotelListDto();
        }
        
        public void getHotelListDtoAsync()
        {
            base.Channel.getHotelListDtoAsync();
        }
        
        public void getHotelDto()
        {
            base.Channel.getHotelDto();
        }
        
        public void getHotelDtoAsync()
        {
            base.Channel.getHotelDtoAsync();
        }
    }
}
