//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI_Hotel_Booking.HotelService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", ConfigurationName="HotelService.HotelWebService")]
    public interface HotelWebService {
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.ws.project.soap.rsi.com/HotelWebService/getHotelListDtoRequest", ReplyAction="http://endpoint.ws.project.soap.rsi.com/HotelWebService/getHotelListDtoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RSI_Hotel_Booking.HotelService.getHotelListDtoResponse getHotelListDto(RSI_Hotel_Booking.HotelService.getHotelListDtoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.ws.project.soap.rsi.com/HotelWebService/getHotelListDtoRequest", ReplyAction="http://endpoint.ws.project.soap.rsi.com/HotelWebService/getHotelListDtoResponse")]
        System.Threading.Tasks.Task<RSI_Hotel_Booking.HotelService.getHotelListDtoResponse> getHotelListDtoAsync(RSI_Hotel_Booking.HotelService.getHotelListDtoRequest request);
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.ws.project.soap.rsi.com/HotelWebService/getHotelDtoRequest", ReplyAction="http://endpoint.ws.project.soap.rsi.com/HotelWebService/getHotelDtoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RSI_Hotel_Booking.HotelService.getHotelDtoResponse getHotelDto(RSI_Hotel_Booking.HotelService.getHotelDtoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.ws.project.soap.rsi.com/HotelWebService/getHotelDtoRequest", ReplyAction="http://endpoint.ws.project.soap.rsi.com/HotelWebService/getHotelDtoResponse")]
        System.Threading.Tasks.Task<RSI_Hotel_Booking.HotelService.getHotelDtoResponse> getHotelDtoAsync(RSI_Hotel_Booking.HotelService.getHotelDtoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/")]
    public partial class hotelListDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string exhibitionPhotoField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string exhibitionPhoto {
            get {
                return this.exhibitionPhotoField;
            }
            set {
                this.exhibitionPhotoField = value;
                this.RaisePropertyChanged("exhibitionPhoto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/")]
    public partial class placeDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private double distanceField;
        
        private bool distanceFieldSpecified;
        
        private string nameField;
        
        private string photoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
                this.RaisePropertyChanged("distance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distanceSpecified {
            get {
                return this.distanceFieldSpecified;
            }
            set {
                this.distanceFieldSpecified = value;
                this.RaisePropertyChanged("distanceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
                this.RaisePropertyChanged("photo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/")]
    public partial class hotelDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string additionalInformationsField;
        
        private string addressField;
        
        private string nameField;
        
        private placeDto[] nearbyPlacesField;
        
        private int rateField;
        
        private bool rateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string additionalInformations {
            get {
                return this.additionalInformationsField;
            }
            set {
                this.additionalInformationsField = value;
                this.RaisePropertyChanged("additionalInformations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nearbyPlaces", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public placeDto[] nearbyPlaces {
            get {
                return this.nearbyPlacesField;
            }
            set {
                this.nearbyPlacesField = value;
                this.RaisePropertyChanged("nearbyPlaces");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
                this.RaisePropertyChanged("rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rateSpecified {
            get {
                return this.rateFieldSpecified;
            }
            set {
                this.rateFieldSpecified = value;
                this.RaisePropertyChanged("rateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHotelListDto", WrapperNamespace="http://endpoint.ws.project.soap.rsi.com/", IsWrapped=true)]
    public partial class getHotelListDtoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public getHotelListDtoRequest() {
        }
        
        public getHotelListDtoRequest(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHotelListDtoResponse", WrapperNamespace="http://endpoint.ws.project.soap.rsi.com/", IsWrapped=true)]
    public partial class getHotelListDtoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RSI_Hotel_Booking.HotelService.hotelListDto[] @return;
        
        public getHotelListDtoResponse() {
        }
        
        public getHotelListDtoResponse(RSI_Hotel_Booking.HotelService.hotelListDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHotelDto", WrapperNamespace="http://endpoint.ws.project.soap.rsi.com/", IsWrapped=true)]
    public partial class getHotelDtoRequest {
        
        public getHotelDtoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHotelDtoResponse", WrapperNamespace="http://endpoint.ws.project.soap.rsi.com/", IsWrapped=true)]
    public partial class getHotelDtoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RSI_Hotel_Booking.HotelService.hotelDto[] @return;
        
        public getHotelDtoResponse() {
        }
        
        public getHotelDtoResponse(RSI_Hotel_Booking.HotelService.hotelDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HotelWebServiceChannel : RSI_Hotel_Booking.HotelService.HotelWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelWebServiceClient : System.ServiceModel.ClientBase<RSI_Hotel_Booking.HotelService.HotelWebService>, RSI_Hotel_Booking.HotelService.HotelWebService {
        
        public HotelWebServiceClient() {
        }
        
        public HotelWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RSI_Hotel_Booking.HotelService.getHotelListDtoResponse RSI_Hotel_Booking.HotelService.HotelWebService.getHotelListDto(RSI_Hotel_Booking.HotelService.getHotelListDtoRequest request) {
            return base.Channel.getHotelListDto(request);
        }
        
        public RSI_Hotel_Booking.HotelService.hotelListDto[] getHotelListDto(long arg0) {
            RSI_Hotel_Booking.HotelService.getHotelListDtoRequest inValue = new RSI_Hotel_Booking.HotelService.getHotelListDtoRequest();
            inValue.arg0 = arg0;
            RSI_Hotel_Booking.HotelService.getHotelListDtoResponse retVal = ((RSI_Hotel_Booking.HotelService.HotelWebService)(this)).getHotelListDto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RSI_Hotel_Booking.HotelService.getHotelListDtoResponse> RSI_Hotel_Booking.HotelService.HotelWebService.getHotelListDtoAsync(RSI_Hotel_Booking.HotelService.getHotelListDtoRequest request) {
            return base.Channel.getHotelListDtoAsync(request);
        }
        
        public System.Threading.Tasks.Task<RSI_Hotel_Booking.HotelService.getHotelListDtoResponse> getHotelListDtoAsync(long arg0) {
            RSI_Hotel_Booking.HotelService.getHotelListDtoRequest inValue = new RSI_Hotel_Booking.HotelService.getHotelListDtoRequest();
            inValue.arg0 = arg0;
            return ((RSI_Hotel_Booking.HotelService.HotelWebService)(this)).getHotelListDtoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RSI_Hotel_Booking.HotelService.getHotelDtoResponse RSI_Hotel_Booking.HotelService.HotelWebService.getHotelDto(RSI_Hotel_Booking.HotelService.getHotelDtoRequest request) {
            return base.Channel.getHotelDto(request);
        }
        
        public RSI_Hotel_Booking.HotelService.hotelDto[] getHotelDto() {
            RSI_Hotel_Booking.HotelService.getHotelDtoRequest inValue = new RSI_Hotel_Booking.HotelService.getHotelDtoRequest();
            RSI_Hotel_Booking.HotelService.getHotelDtoResponse retVal = ((RSI_Hotel_Booking.HotelService.HotelWebService)(this)).getHotelDto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RSI_Hotel_Booking.HotelService.getHotelDtoResponse> RSI_Hotel_Booking.HotelService.HotelWebService.getHotelDtoAsync(RSI_Hotel_Booking.HotelService.getHotelDtoRequest request) {
            return base.Channel.getHotelDtoAsync(request);
        }
        
        public System.Threading.Tasks.Task<RSI_Hotel_Booking.HotelService.getHotelDtoResponse> getHotelDtoAsync() {
            RSI_Hotel_Booking.HotelService.getHotelDtoRequest inValue = new RSI_Hotel_Booking.HotelService.getHotelDtoRequest();
            return ((RSI_Hotel_Booking.HotelService.HotelWebService)(this)).getHotelDtoAsync(inValue);
        }
    }
}
