//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI_Hotel_Booking.RaportService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", ConfigurationName="RaportService.BookingReportWebService")]
    public interface BookingReportWebService {
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.ws.project.soap.rsi.com/BookingReportWebService/getBookingConfirm" +
            "ationRequest", ReplyAction="http://endpoint.ws.project.soap.rsi.com/BookingReportWebService/getBookingConfirm" +
            "ationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RSI_Hotel_Booking.RaportService.IOException), Action="http://endpoint.ws.project.soap.rsi.com/BookingReportWebService/getBookingConfirm" +
            "ation/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RSI_Hotel_Booking.RaportService.getBookingConfirmationResponse getBookingConfirmation(RSI_Hotel_Booking.RaportService.getBookingConfirmationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.ws.project.soap.rsi.com/BookingReportWebService/getBookingConfirm" +
            "ationRequest", ReplyAction="http://endpoint.ws.project.soap.rsi.com/BookingReportWebService/getBookingConfirm" +
            "ationResponse")]
        System.Threading.Tasks.Task<RSI_Hotel_Booking.RaportService.getBookingConfirmationResponse> getBookingConfirmationAsync(RSI_Hotel_Booking.RaportService.getBookingConfirmationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBookingConfirmation", WrapperNamespace="http://endpoint.ws.project.soap.rsi.com/", IsWrapped=true)]
    public partial class getBookingConfirmationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public getBookingConfirmationRequest() {
        }
        
        public getBookingConfirmationRequest(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBookingConfirmationResponse", WrapperNamespace="http://endpoint.ws.project.soap.rsi.com/", IsWrapped=true)]
    public partial class getBookingConfirmationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public getBookingConfirmationResponse() {
        }
        
        public getBookingConfirmationResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookingReportWebServiceChannel : RSI_Hotel_Booking.RaportService.BookingReportWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookingReportWebServiceClient : System.ServiceModel.ClientBase<RSI_Hotel_Booking.RaportService.BookingReportWebService>, RSI_Hotel_Booking.RaportService.BookingReportWebService {
        
        public BookingReportWebServiceClient() {
        }
        
        public BookingReportWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookingReportWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingReportWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingReportWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RSI_Hotel_Booking.RaportService.getBookingConfirmationResponse RSI_Hotel_Booking.RaportService.BookingReportWebService.getBookingConfirmation(RSI_Hotel_Booking.RaportService.getBookingConfirmationRequest request) {
            return base.Channel.getBookingConfirmation(request);
        }
        
        public byte[] getBookingConfirmation(long arg0) {
            RSI_Hotel_Booking.RaportService.getBookingConfirmationRequest inValue = new RSI_Hotel_Booking.RaportService.getBookingConfirmationRequest();
            inValue.arg0 = arg0;
            RSI_Hotel_Booking.RaportService.getBookingConfirmationResponse retVal = ((RSI_Hotel_Booking.RaportService.BookingReportWebService)(this)).getBookingConfirmation(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RSI_Hotel_Booking.RaportService.getBookingConfirmationResponse> RSI_Hotel_Booking.RaportService.BookingReportWebService.getBookingConfirmationAsync(RSI_Hotel_Booking.RaportService.getBookingConfirmationRequest request) {
            return base.Channel.getBookingConfirmationAsync(request);
        }
        
        public System.Threading.Tasks.Task<RSI_Hotel_Booking.RaportService.getBookingConfirmationResponse> getBookingConfirmationAsync(long arg0) {
            RSI_Hotel_Booking.RaportService.getBookingConfirmationRequest inValue = new RSI_Hotel_Booking.RaportService.getBookingConfirmationRequest();
            inValue.arg0 = arg0;
            return ((RSI_Hotel_Booking.RaportService.BookingReportWebService)(this)).getBookingConfirmationAsync(inValue);
        }
    }
}
