//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI_Hotel_Booking.UserRatingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", ConfigurationName="UserRatingService.UserRatingWebService")]
    public interface UserRatingWebService {
        
        // CODEGEN: Parametr „arg0” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.ws.project.soap.rsi.com/UserRatingWebService/addUserRatingRequest" +
            "", ReplyAction="http://endpoint.ws.project.soap.rsi.com/UserRatingWebService/addUserRatingRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RSI_Hotel_Booking.UserRatingService.addUserRatingResponse addUserRating(RSI_Hotel_Booking.UserRatingService.addUserRatingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.ws.project.soap.rsi.com/UserRatingWebService/addUserRatingRequest" +
            "", ReplyAction="http://endpoint.ws.project.soap.rsi.com/UserRatingWebService/addUserRatingRespons" +
            "e")]
        System.Threading.Tasks.Task<RSI_Hotel_Booking.UserRatingService.addUserRatingResponse> addUserRatingAsync(RSI_Hotel_Booking.UserRatingService.addUserRatingRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/")]
    public partial class userRatingDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string personNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string personName {
            get {
                return this.personNameField;
            }
            set {
                this.personNameField = value;
                this.RaisePropertyChanged("personName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addUserRating", WrapperNamespace="http://endpoint.ws.project.soap.rsi.com/", IsWrapped=true)]
    public partial class addUserRatingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RSI_Hotel_Booking.UserRatingService.userRatingDto arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg2;
        
        public addUserRatingRequest() {
        }
        
        public addUserRatingRequest(RSI_Hotel_Booking.UserRatingService.userRatingDto arg0, long arg1, long arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addUserRatingResponse", WrapperNamespace="http://endpoint.ws.project.soap.rsi.com/", IsWrapped=true)]
    public partial class addUserRatingResponse {
        
        public addUserRatingResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserRatingWebServiceChannel : RSI_Hotel_Booking.UserRatingService.UserRatingWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserRatingWebServiceClient : System.ServiceModel.ClientBase<RSI_Hotel_Booking.UserRatingService.UserRatingWebService>, RSI_Hotel_Booking.UserRatingService.UserRatingWebService {
        
        public UserRatingWebServiceClient() {
        }
        
        public UserRatingWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserRatingWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserRatingWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserRatingWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RSI_Hotel_Booking.UserRatingService.addUserRatingResponse RSI_Hotel_Booking.UserRatingService.UserRatingWebService.addUserRating(RSI_Hotel_Booking.UserRatingService.addUserRatingRequest request) {
            return base.Channel.addUserRating(request);
        }
        
        public void addUserRating(RSI_Hotel_Booking.UserRatingService.userRatingDto arg0, long arg1, long arg2) {
            RSI_Hotel_Booking.UserRatingService.addUserRatingRequest inValue = new RSI_Hotel_Booking.UserRatingService.addUserRatingRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            RSI_Hotel_Booking.UserRatingService.addUserRatingResponse retVal = ((RSI_Hotel_Booking.UserRatingService.UserRatingWebService)(this)).addUserRating(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RSI_Hotel_Booking.UserRatingService.addUserRatingResponse> RSI_Hotel_Booking.UserRatingService.UserRatingWebService.addUserRatingAsync(RSI_Hotel_Booking.UserRatingService.addUserRatingRequest request) {
            return base.Channel.addUserRatingAsync(request);
        }
        
        public System.Threading.Tasks.Task<RSI_Hotel_Booking.UserRatingService.addUserRatingResponse> addUserRatingAsync(RSI_Hotel_Booking.UserRatingService.userRatingDto arg0, long arg1, long arg2) {
            RSI_Hotel_Booking.UserRatingService.addUserRatingRequest inValue = new RSI_Hotel_Booking.UserRatingService.addUserRatingRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((RSI_Hotel_Booking.UserRatingService.UserRatingWebService)(this)).addUserRatingAsync(inValue);
        }
    }
}
