//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI_Hotel_Booking.SecurityService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", ConfigurationName="SecurityService.SecurityWebService")]
    public interface SecurityWebService {
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.ws.project.soap.rsi.com/SecurityWebService/registerRequest", ReplyAction="http://endpoint.ws.project.soap.rsi.com/SecurityWebService/registerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RSI_Hotel_Booking.SecurityService.registerResponse register(RSI_Hotel_Booking.SecurityService.registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.ws.project.soap.rsi.com/SecurityWebService/registerRequest", ReplyAction="http://endpoint.ws.project.soap.rsi.com/SecurityWebService/registerResponse")]
        System.Threading.Tasks.Task<RSI_Hotel_Booking.SecurityService.registerResponse> registerAsync(RSI_Hotel_Booking.SecurityService.registerRequest request);
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.ws.project.soap.rsi.com/SecurityWebService/loginRequest", ReplyAction="http://endpoint.ws.project.soap.rsi.com/SecurityWebService/loginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RSI_Hotel_Booking.SecurityService.loginResponse login(RSI_Hotel_Booking.SecurityService.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.ws.project.soap.rsi.com/SecurityWebService/loginRequest", ReplyAction="http://endpoint.ws.project.soap.rsi.com/SecurityWebService/loginResponse")]
        System.Threading.Tasks.Task<RSI_Hotel_Booking.SecurityService.loginResponse> loginAsync(RSI_Hotel_Booking.SecurityService.loginRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/")]
    public partial class userDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="register", WrapperNamespace="http://endpoint.ws.project.soap.rsi.com/", IsWrapped=true)]
    public partial class registerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RSI_Hotel_Booking.SecurityService.userDto arg0;
        
        public registerRequest() {
        }
        
        public registerRequest(RSI_Hotel_Booking.SecurityService.userDto arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerResponse", WrapperNamespace="http://endpoint.ws.project.soap.rsi.com/", IsWrapped=true)]
    public partial class registerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long @return;
        
        public registerResponse() {
        }
        
        public registerResponse(long @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://endpoint.ws.project.soap.rsi.com/", IsWrapped=true)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RSI_Hotel_Booking.SecurityService.userDto arg0;
        
        public loginRequest() {
        }
        
        public loginRequest(RSI_Hotel_Booking.SecurityService.userDto arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://endpoint.ws.project.soap.rsi.com/", IsWrapped=true)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long @return;
        
        public loginResponse() {
        }
        
        public loginResponse(long @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecurityWebServiceChannel : RSI_Hotel_Booking.SecurityService.SecurityWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityWebServiceClient : System.ServiceModel.ClientBase<RSI_Hotel_Booking.SecurityService.SecurityWebService>, RSI_Hotel_Booking.SecurityService.SecurityWebService {
        
        public SecurityWebServiceClient() {
        }
        
        public SecurityWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RSI_Hotel_Booking.SecurityService.registerResponse RSI_Hotel_Booking.SecurityService.SecurityWebService.register(RSI_Hotel_Booking.SecurityService.registerRequest request) {
            return base.Channel.register(request);
        }
        
        public long register(RSI_Hotel_Booking.SecurityService.userDto arg0) {
            RSI_Hotel_Booking.SecurityService.registerRequest inValue = new RSI_Hotel_Booking.SecurityService.registerRequest();
            inValue.arg0 = arg0;
            RSI_Hotel_Booking.SecurityService.registerResponse retVal = ((RSI_Hotel_Booking.SecurityService.SecurityWebService)(this)).register(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RSI_Hotel_Booking.SecurityService.registerResponse> RSI_Hotel_Booking.SecurityService.SecurityWebService.registerAsync(RSI_Hotel_Booking.SecurityService.registerRequest request) {
            return base.Channel.registerAsync(request);
        }
        
        public System.Threading.Tasks.Task<RSI_Hotel_Booking.SecurityService.registerResponse> registerAsync(RSI_Hotel_Booking.SecurityService.userDto arg0) {
            RSI_Hotel_Booking.SecurityService.registerRequest inValue = new RSI_Hotel_Booking.SecurityService.registerRequest();
            inValue.arg0 = arg0;
            return ((RSI_Hotel_Booking.SecurityService.SecurityWebService)(this)).registerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RSI_Hotel_Booking.SecurityService.loginResponse RSI_Hotel_Booking.SecurityService.SecurityWebService.login(RSI_Hotel_Booking.SecurityService.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public long login(RSI_Hotel_Booking.SecurityService.userDto arg0) {
            RSI_Hotel_Booking.SecurityService.loginRequest inValue = new RSI_Hotel_Booking.SecurityService.loginRequest();
            inValue.arg0 = arg0;
            RSI_Hotel_Booking.SecurityService.loginResponse retVal = ((RSI_Hotel_Booking.SecurityService.SecurityWebService)(this)).login(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RSI_Hotel_Booking.SecurityService.loginResponse> RSI_Hotel_Booking.SecurityService.SecurityWebService.loginAsync(RSI_Hotel_Booking.SecurityService.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<RSI_Hotel_Booking.SecurityService.loginResponse> loginAsync(RSI_Hotel_Booking.SecurityService.userDto arg0) {
            RSI_Hotel_Booking.SecurityService.loginRequest inValue = new RSI_Hotel_Booking.SecurityService.loginRequest();
            inValue.arg0 = arg0;
            return ((RSI_Hotel_Booking.SecurityService.SecurityWebService)(this)).loginAsync(inValue);
        }
    }
}
