//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI_Hotel_Booking.RoomService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://endpoint.ws.project.soap.rsi.com/", ConfigurationName="RSI_Hotel_Booking.RoomService.RoomWebService")]
    public interface RoomWebService
    {
        
        [System.ServiceModel.OperationContractAttribute()]
        void getRoomListDtos();
        
        [System.ServiceModel.OperationContractAttribute()]
        void getRoomListDtosAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void getRoomDto();
        
        [System.ServiceModel.OperationContractAttribute()]
        void getRoomDtoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RoomWebServiceChannel : RSI_Hotel_Booking.RoomService.RoomWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomWebServiceClient : System.ServiceModel.ClientBase<RSI_Hotel_Booking.RoomService.RoomWebService>, RSI_Hotel_Booking.RoomService.RoomWebService
    {
        
        public RoomWebServiceClient()
        {
        }
        
        public RoomWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public RoomWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RoomWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RoomWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void getRoomListDtos()
        {
            base.Channel.getRoomListDtos();
        }
        
        public void getRoomListDtosAsync()
        {
            base.Channel.getRoomListDtosAsync();
        }
        
        public void getRoomDto()
        {
            base.Channel.getRoomDto();
        }
        
        public void getRoomDtoAsync()
        {
            base.Channel.getRoomDtoAsync();
        }
    }
}
